### GENERAL SETTINGS ###

# Site settings
title: Empiria
description: "Find new ways to play with your standard 52-Card deck for both single and multiplayer games."
analytics: UA-58200120-1
baseurl: "/empiria-card-game"
url: "http://chibicritters.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:
  primary: "#5C832F"
  primary_rgb: "92,131,47"
  secondary: "#363942"
  secondary_rgb: "54,57,66"
  link: "#5C832F"
  link_hover: "#284907"
  footer_heading: "#ffffff"
  footer_content: "#D8CAA8"


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Ivan Montiel
    position: Game Designer
    text: Designer and game tester for Empiria
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:idmontie@asu.edu
      - title: twitter
        url: http://twitter.com/idmontie
  - name: Daniela Howe
    position: Graphics Artist
    text: Graphics artists for Empiria
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dlhowe@asu.edu
      - title: twitter
        url: http://twitter.com/nagoshiasumari

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Find new ways to play with your standard 52-Card deck for both single and multiplayer games."
